title: "APEC Workshop: Launch for Ocean Tech Solutions"
description: >
  Collaborating to Advance Innovative Ocean Technologies Across the Asia-Pacific

baseurl: "/ocean-tech-solutions-workshop"
url: "https://usapecrise.github.io"

markdown: kramdown

logo: "/css/2016_style/img/icon-large.png"

social: []

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
